[tool.isort]
include_training_comma=true
line_length = 100
lines_after_imports = 2
multi_line_outputs = 3
profile = "black"

[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ['py311']

[tool.pylint.master]
extension-pkg-allow-list = [
    "pydantic.error_wrappers",
]

[tool.pylint.format]
max-line-length = 100

[tool.mypy]
python_version = 3.11
warn_return_any = true

[[tool.mypy.overrides]]
module = [
    "sqlalchemy",
]
ignore_missing_imports = true

[tool.flake8]
ignore = "E203,W503,W504"
max-line-length = 100
exclude = "tests/*"
max-complexity = 10
