[tool.black]
line-length = 120
exclude = '''
(
    .mypy_cache
    | .pytest_cache
    | .venv
)
'''

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
ignore = "E203,W503,W504,F401"
max-line-length = 150
exclude = "tests/*"
max-complexity = 10