openapi: '3.0.2'
info:
  version: 0.0.1
  title: Web app test api

paths:
  $ref: ./paths/index.yaml

components:
  schemas:
    $ref: ./components/schemas/index.yaml
  securitySchemas:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionId

servers:
  - url: '{server}'
    variables:
      server:
        default: http://localhost:8080